version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      kafka-network:
        ipv4_address: 172.20.0.9
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      kafka-network:
        ipv4_address: 172.20.0.10
    restart: always

  prometheus-mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb_exporter
    environment:
    - MONGODB_URI=mongodb://monitorUser:monitorPassword@172.20.0.4:27017/admin # Use the correct IP address for MongoDB
    command: "--mongodb.uri=mongodb://monitorUser:monitorPassword@172.20.0.4:27017/admin --collect-all"
    ports:
      - "9216:9216"
    networks:
      kafka-network:
        ipv4_address: 172.20.0.8
    restart: always

networks:
  kafka-network:
    external: true  # We use the external kafka-network where MongoDB is already deployed

volumes:
  grafana_data:
